//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblProduto
    {
        public int Id { get; set; }

        [Required(ErrorMessage ="Required")]
        public string Nome { get; set; }
        [Required(ErrorMessage = "Required")]
        public string Descricao { get; set; }
        [Required(ErrorMessage = "Required")]
        public bool Ativo { get; set; }
        [Required(ErrorMessage = "Required")]
        public bool Perecivel { get; set; }
        public int Categoria { get; set; }
    }
}
